# Generated by Django 6.0.2 on 2026-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
