# Generated by Django 6.0.2 on 2026-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='qr_code_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
