# Generated by Django 6.0.2 on 2026-02-19 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_sessions', '0002_attendancesession_qr_code_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='end_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
