# Generated by Django 6.0.2 on 2026-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_sessions', '0003_attendancesession_date_attendancesession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10),
        ),
    ]
