name: mmu_attendance_app
description: "MMU Student Attendance Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  http: ^1.2.0

  # Local storage / shared preferences
  shared_preferences: ^2.2.3

  # QR Code scanner
  mobile_scanner: ^5.2.3

  # Icons
  cupertino_icons: ^1.0.6

  # Image picker for profile
  image_picker: ^1.0.7

  # Intl for date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
